services:
  grafana:
    container_name: drasi-grafana-plugin-test
    build:
      context: .
      dockerfile: Dockerfile.grafana
    ports:
      - '3000:3000'
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=live
      - GF_SERVER_PROTOCOL=http
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=drasi-signalr
      - GF_PLUGINS_ENABLE_ALPHA=true
      - GF_DEFAULT_APP_MODE=development
    extra_hosts:
      - "host.docker.internal:host-gateway"
  drasi:
    container_name: drasi-grafana-plugin-host
    build:
      context: ./provisioning/drasi
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kube-config:/root/.kube
      - data-volume:/data
    ports:
      - '8080:8080'
volumes:
  kube-config:
  data-volume:
